---

- name: update
  apt: 
    update_cache: yes
    upgrade: "yes"
- name: Installation dependances
  apt: 
    name: "{{ item }}"
    state: latest        
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - lsb-release
    - gnupg
    - python3-pip
    - virtualenv
    - python3-setuptools
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Module for Python
  pip:
    name: docker    

- name: Add the remote user with a bash shell, appending the group 'docker'
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Configure docker to start on boot
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: 
    - docker
    - containerd

- name: Enable ipv6 in Docker
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'    

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted    

- name: Copy app
  ansible.builtin.copy:
    src: ../app/
    dest: /opt/bingo
    owner: root
    group: root
    mode: '0644'

- name: Chmod file
  ansible.builtin.file:
    path: /opt/bingo/bingo/bin/bingo
    state: touch
    mode: u+x

- name: Template config for bingo
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /opt/bingo/config.yaml
    owner: root
    group: root
    mode: '0644'        

- name: Run Bingo
  ansible.builtin.shell:
    cmd: |
      docker compose up -d --build
    chdir: /opt/bingo
